CPINC-2781 (YV's Jira) hotfix
atlasapi/atlas-feeds pull request #289
Opened 2022-09-16 10:48 UTC by EmiEnache

Amazon sends us many images for some content, in a diverse set of language+country locales. Our atlas model cannot currently store locale on image level, so we ditch it. Unfortunately this means that sometimes we don't send youview the image they want.
This fixes it for a specific very high profile brand as a quick resolution while we plan to work on improving the atlas-model to add locale at a later date.

2022-09-16 10:52 UTC, tristanbeardmore-gray requested changes

2022-09-16 10:52 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        imageUrl = content.getImage();
```suggestion
        } else {
            imageUrl = content.getImage();
        }
```

2022-09-16 10:52 UTC, tristanbeardmore-gray commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
Add a comment referencing a ticket number

2022-09-16 10:57 UTC, pawel-mtbcst commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        imageUrl = content.getImage();
you're overwriting the imageUrl

2022-09-16 10:58 UTC, pawel-mtbcst commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        if (RINGS_OF_POWER_BRAND_URI.equals(content.getCanonicalUri())) {
I know it's quick and temporary, but I would add a TODO or FIXME comment mentioning that this should be removed.

2022-09-16 12:40 UTC, EmiEnache commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
Does the .map(imageUrl -> ) part of the method return expected results if the return of resolveImageUrl is Optional.empty()? if e.g. content is null.

I'm not sure I see what benefits that whole block adds though, but I do see the benefits of a resolveImageUrl method. 

How about something like this:
`    private Optional<RelatedMaterialType> generateRelatedMaterial(@Nullable Content content) {

        java.util.Optional<String> optionalImage = resolveImageUrl(content);
        if (!optionalImage.isPresent()) {
            return Optional.absent();
        }
        
        String imageUrl = optionalImage.get();

        ExtendedRelatedMaterialType relatedMaterial = new ExtendedRelatedMaterialType();

        relatedMaterial.setHowRelated(generateHowRelated());
        relatedMaterial.setFormat(generateFormat());
        relatedMaterial.setMediaLocator(generateMediaLocator(imageUrl));
        relatedMaterial.setContentProperties(generateContentProperties());

        return Optional.of(relatedMaterial);
    }

    private java.util.Optional<String> resolveImageUrl(@Nullable Content content) {

        if (content == null) {
            return java.util.Optional.empty();
        }
        // temporary hotfix / workaround for CPINC-2781; TODO refactor after ENG-1419
        if (RINGS_OF_POWER_BRAND_URI.equals(content.getCanonicalUri())) {
            return java.util.Optional.of(RINGS_OF_POWER_BRAND_ENGLISH_IMAGE);
        } 

        if (StringUtils.isNotBlank(content.getImage())) {
            return java.util.Optional.of(content.getImage());
        }
        
        // As requested by YV, if it's a film with no image, inject a default image.
        if (content instanceof Film) {
            return java.util.Optional.of(AMAZON_DEFAULT_FILL_IN_IMAGE_URL);
        }

        return java.util.Optional.empty();
    }`

2022-09-16 13:03 UTC, pawel-mtbcst commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
That's true - my code sample did not take into account that there are guavas Optionals there instead of JDKs, however, we should replace guavas Optional in favor of JDKs, so from that perspective, I stand with my solution.

Additionally, this is a private method and its result is not re-returned anywhere outside of the class so it should be a fairly easy refactor. 
I know it's supposed to be a quick fix that we additionally want to deploy today so I'm not insisting on doing this right now, but it should be the way we improve the code.

And yes - map will be executed only when optional is not empty, that why we should use Optionals in the first place - it's massive simplification in a lot of cases, so it will work as expected (meaning - it won't instantiate `ExtendedRelatedMaterialType` when `content == null` or when `content.getImage() == null && !content instanceOf Film` )


For example using JDKs guava you could replace this (lines ~350)
```
           relatedMaterial = generateRelatedMaterial(content);
            if (!relatedMaterial.isPresent()) {
                relatedMaterial = generateRelatedMaterial(item);
            }
```       

with this:            
```
            relatedMaterial = generateRelatedMaterial(content)
                    .or(() -> generateRelatedMaterial(item));
```

2022-09-16 13:04 UTC, EmiEnache commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
I think this way the behaviour is generateRelatedMaterial is easier and quicker to understand – there's no need to think about what the result of the map in null vs non-null.

2022-09-16 13:06 UTC, pawel-mtbcst commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
@EmiEnache 
What do you mean `null vs non-null` ?
Optional exists specifically so that you don't have to think and care about null values.

2022-09-16 13:19 UTC, EmiEnache commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
Sorry, by that I just meant the cases where the imageUrl ends up being an empty optional. 

My point was that it wasn't immediately obvious to me what the return of generateRelatedMaterial was

2022-09-16 13:32 UTC, pawel-mtbcst commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
@EmiEnache 
But it's optional - it's never null.
For me it's far more obvious - we resolve `imageUri` somehow (doesn't really matter how on this abstraction level), and if we have it - we instantiate `ExtendedRelatedMaterialType` based on it).


Some of Martin Fowler thoughts worth mentioning here:
https://martinfowler.com/bliki/FunctionLength.html

Taking the Clean Code principles even more seriously, I would create 3 methods based on this:
```
    private java.util.Optional<RelatedMaterialType> generateRelatedMaterial(@Nullable Content content) {
        return resolveImageUrl(content)
                .map(this::createImageRelatedMaterial);
    }

    private ExtendedRelatedMaterialType createImageRelatedMaterial(String imageUrl) {
        ExtendedRelatedMaterialType relatedMaterial = new ExtendedRelatedMaterialType();
        relatedMaterial.setHowRelated(generateHowRelated());
        relatedMaterial.setFormat(generateFormat());
        relatedMaterial.setMediaLocator(generateMediaLocator(imageUrl));
        relatedMaterial.setContentProperties(generateContentProperties());
        return relatedMaterial;
    }

    private java.util.Optional<String> resolveImageUrl(@Nullable Content content) {
        if (content == null)
            return empty();

        // TODO: temporary hotfix / workaround for CPINC-2781; refactor after ENG-1419
        if (RINGS_OF_POWER_BRAND_URI.equals(content.getCanonicalUri()))
            return java.util.Optional.of(RINGS_OF_POWER_BRAND_ENGLISH_IMAGE);

        if (StringUtils.isNotBlank(content.getImage())) return java.util.Optional.of(content.getImage());

        // As requested by YV, if it's a film with no image, inject a default image.
        if (content instanceof Film) return java.util.Optional.of(AMAZON_DEFAULT_FILL_IN_IMAGE_URL);

        return empty();
    }
```

2022-09-16 15:27 UTC, EmiEnache commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
As discussed in Slack, the code will be deployed since it needs to go live today without all the changes being discussed here as they relate more to style than functionality, and the conversation will be continued via call on Tuesday (ideally we put here a summary of that call afterwards, or link to any other place of discussion)

2022-09-16 15:28 UTC, merged

2022-09-21 14:44 UTC, EmiEnache commented on src/main/java/org/atlasapi/feeds/youview/amazon/AmazonGroupInformationGenerator.java
> +        String imageUrl;
.map() is a method of java Optional which will do something if there is an optional, otherwise returns Optional.empty(). Helps keep code clear and concise without having to worry about whether the optional has a value or not.

The suggestions were presented as more options regarding code style. We agreed it didn't make sense to make further changes given it was a hotfix, and that we could have a conversation as a team about what code style changes we'd like to make.